### ISSUE TITLE
What does { someSymbol -> 1 } mean?

### ISSUE THREAD

**Issue by Dimension4** [matjin/infersharp-vs-extension#1]
Hey,

I'm trying to figure out what the `-> 1` part means in `DOTNET_RESOURCE_LEAK`. For example `Leaked { n$3 -> 1, n$4 -> 0 }`. I think the `n$k` part represents the k-th value in the current stack frame (arguments and locals) but I don't know what the arrow and the number afterwards denote.

**Comment by matjin** [comment]
The '-> 1' means that the resource is being leaked. We will be simplifying the messaging in the future to remove reporting on resources that aren't leaked (indicated by -> 0). 

The n$k item is actually just a temporary identifier attached to an object that isn't assigned to a local variable (were it assigned to a local variable, it should have the variable name (or a %k identifier in the event that the name is not available). 

To identify the relevant resource, you should look at the types -- if it says Leaked "{ n$3 -> 1, n$4 -> 0 } at type(s) X and Y" you should look for a type in your method that is of type X and is instantiated inline without assignment to a local variable -- for example, some people might write something like

"using (StreamWriter writer = new StreamWriter(new FileStream(), Encoding.Default)) {...}" 

which leaves the FileStream inside as a leaked resource that will be identified by an n$k of type FileStream.

**Comment by Dimension4** [comment]
Thanks a lot for the explanation. So if 1 means leak and 0 means no leak, what does -1 mean? I had a couple of those as well.

**Comment by matjin** [comment]
Sorry for the lack of clarity -- basically, you should only pay attention to resources for which the value is 1; non-positive values indicate the absence of a leak (and you shouldn't see 2 or greater anyway). 

This is a backend technicality we will be fixing soon -- we'll only display the leaked resources and exclude the non-leaked stuff from the warning message altogether.

**Comment by Dimension4** [comment]
Alright, thanks for clarifying it!
